### ISSUE TITLE
how to publish a dataset for local testing?

### ISSUE THREAD

**Issue by seralf** [AKSW/KBox#10]
HI
I wonder if it's possible to test the service with my own RDF data locally: I mean creating a small knowledge base and expose it by SPARQL.
Reading at "Although you can create your own KNS service and publish your datasets,..." it seems possible but following the README and the usage from command line I don't understand how.
For example the indexing of files in a directory does something and create a .kb file, but I'm not sure if I have to use this file in some way for exposing it by SPARQL?

thanks for any advice/suggestion

**Comment by digamarx** [comment]
hey...
thanks for your question...

Have you tried the command:

``
* -install -kb <kb-URL> -index <indexFile>    - Install a given index in a given knowledge base URL.
´´
