### ISSUE TITLE
graph groups

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/KBox#36]
Does kbox support graph groups? Our dataset SNIK has the following structure:

graph group: http://www.snik.eu/ontology
graphs: http://www.snik.eu/ontology/bb, http://www.snik.eu/ontology/meta, ...

This allows one to query the whole dataset at once using the graph group, or target a subset if required by using one of the graphs inside the graph group.

Is that possible with kbox or is that out of scope?

**Comment by edgardmarx** [comment]
If both ontologies are uploaded in separated files, this is possible.
You can read more here: https://github.com/AKSW/KBox#how-can-i-query-multi-bases
