### ISSUE TITLE
Wrong service link for the browser

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/KBox#40]
```
docker run -p 8080:8080 aksw/kbox -server -kb "http://www.snik.eu/ontology" -install
Loading Model...
Installing  99% [===================> ]  [2579465/2580713] ETA: 00:00:01
Publishing service on http://localhost:8080/kbox/query
Service up and running ;-) ..
```
But  `http://localhost:8080/kbox/query` returns a 404 error: `Error 404: Service Description: /kbox/query`.
The correct URL seems to be <http://localhost:8080/>, please correct the link.

**Comment by edgardmarx** [comment]
This issue is related to docker.
Docker forces you to give a name to the machine using the pragma `--name` as specified in the step 4 here: https://github.com/AKSW/KBox#using-kbox-with-docker

**Comment by KonradHoeffner** [comment]
Using the --name pragma does not resolve the issue:

    docker run -p 8080:8080 --name myendpoint2 aksw/kbox -server -kb "https://www.w3.org/2000/01/rdf-schema" -install

Still, `https://localhost:8080` works but `http://localhost:8080/kbox/query` returns a 404.

**Comment by edgardmarx** [comment]
Hi @KonradHoeffner , 

Thanks for reporting the issue once more.
Let me see if I can understand the issue.
As far as I understood, KBox client UI is working in localhost:8080, and there is no issue there.
I made an internal test running KBox jar file, and I could query the endpoint as well:

```
java -jar kbox-v0.0.2-alpha.jar -sparql "Select ?s {?s ?p ?o} limit 5" -server http://localhost:8080/kbox/sparql
-----------------------------------------------------
| s                                                 |
=====================================================
| <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> |
| <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> |
| <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> |
| <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> |
| <http://www.w3.org/2000/01/rdf-schema#member>     |
-----------------------------------------------------
``` 

The problem that you might be facing is due to running a KBox docker client trying to access the KBox docker server.
In this case, you have to link the client to the server as explained in the item **5** here: https://github.com/AKSW/KBox#using-kbox-with-docker

I guess you missed it.
Could you check if you have any problems after that? 

Thanks

**Comment by edgardmarx** [comment]
Just tested, there is an error with the Docker file, it is not receiving the full arguments.
I will assign this issue to you, so you can try to fix it.

**Comment by KonradHoeffner** [comment]
This is another issue. I fixed the Docker argument bug in https://github.com/AKSW/KBox/pull/43/files.

Now I can do:

    docker run -p 8080:8080 aksw/kbox -server -kb "https://www.w3.org/2000/01/rdf-schema" -install 

And in another terminal:

    docker run --network host  kbox -sparql "Select ?s {?s ?p ?o} limit 5" -server "http://localhost:8080/kbox/sparql" 

And I get a result:

```
-----------------------------------------------------
| s                                                 |
=====================================================
| <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> |
| <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> |
| <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> |
| <http://www.w3.org/1999/02/22-rdf-syntax-ns#rest> |
| <http://www.w3.org/2000/01/rdf-schema#member>     |
-----------------------------------------------------
```

However when I open `http://localhost:8080/kbox/sparq` in the *browser*, then I get `Error 404: Not found: dataset='kbox' service='sparq'`.

In the browser, only `http://localhost` works. This is not related to docker.

**Comment by edgardmarx** [comment]
Ohh ok, the `http://localhost:8080/kbox/sparql` is an endpoint, and will return 404, more precisely `Error 404: Service Description: /kbox/query`.
If you want to use the client, you should use `localhost8080`.
The endpoint located at  `http://localhost:8080/kbox/sparql` is Jena endpoint, and this error is returned by the Jena framework.
I will also add your suggestion `docker run --network host  kbox -sparql ` as standard in docs.

thank you very much

**Comment by KonradHoeffner** [comment]
I know that now after trying for a while, the issue is that other newcomers will have to get through the same struggle as I did. Thus I propose to modify the console output so everyone will know it.

**Comment by edgardmarx** [comment]
Proposition accepted

**Comment by edgardmarx** [comment]
Since this issue is related with service link, I will close it and open another one with command related issue.
