### ISSUE TITLE
Can't stop docker

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/KBox#41]
```
$ docker run -p 8080:8080 aksw/kbox -server -kb "http://www.snik.eu/ontology" -install
Loading Model...
Installing  99% [===================> ]  [2579465/2580713] ETA: 00:00:01
Publishing service on http://localhost:8080/kbox/query
Service up and running ;-) ...
```

Now I can't stop it with CTRL+C. I need `docker kill` in another window to stop it.
Version v0.0.2-alpha.

**Comment by edgardmarx** [comment]
When you run a container your console is detached, so commands that you use will have no effect the the application running at the container.
To attach to a container, please check the documentation https://docs.docker.com/engine/reference/commandline/attach/.
If you think that docker should support this action, please report this issue here: https://github.com/docker

**Comment by KonradHoeffner** [comment]
This is not true, the console is attached, as I cannot enter any other commands.
Also it works just fine with for example Virtuoso:

    docker run openlink/virtuoso-opensource-7

This opens a server, attaches the console without any parameter necessary, and when I hit CTRL+C it stops.

**Comment by KonradHoeffner** [comment]
See also https://docs.docker.com/engine/reference/run/:

## Detached vs foreground

When starting a Docker container, you must first decide if you want to run the container in the background in a “detached” mode or in the *default foreground mode*:

-d=false: Detached mode: Run container in the background, print new container id

**Comment by edgardmarx** [comment]
I see, need to investigate this issue.

**Comment by edgardmarx** [comment]
Please fix the docker file, if there is a way to RUN the app and stop it via command line.

**Comment by KonradHoeffner** [comment]
It was a problem with the ENTRYPOINT, fortunately this got fixed by https://github.com/AKSW/KBox/pull/43 as well.
