### ISSUE TITLE
Docker always forgets what it installed

### ISSUE THREAD

**Issue by KonradHoeffner** [AKSW/KBox#42]
Using aksw/kbox:v0.0.2-alpha, I have to -install the same knowledge base every time I run the container. Please cache the results in order to save time and bandwidth.

**Comment by edgardmarx** [comment]
Yes, KBox container just includes KBox itself not any additional data.
All data installed during the container lifetime is always erased when the container finishes.
If you wish to avoid dereferencing the kb always when running KBox, you should use KBox pip or jar file.

**Comment by KonradHoeffner** [comment]
But that is not unavoidable with Docker. You can use volumes, see https://docs.docker.com/storage/volumes/.

**Comment by edgardmarx** [comment]
OK, then this is not an issue, it is a a feature request.

**Comment by edgardmarx** [comment]
You can devise a method to run KBox using volumes, that will be a great feature.

**Comment by KonradHoeffner** [comment]
I tried it like that but it doesn't work:

    docker run kbox --mount type=bind,source=~/.kbox,target=/root/.kbox -server -kb "https://www.w3.org/2000/01/rdf-schema"  -install

Cancel using CTRL+C

    docker run kbox --mount type=bind,source=~/.kbox,target=/root/.kbox -server -kb "https://www.w3.org/2000/01/rdf-schema"  
    Loading Model...
    Error installing KB: The knowledge base could not be located.
    Try to install it adding the pragma -install to your command.

Can  a Docker expert chime in what is wrong here? It doesn't seem to be able to write there.

**Comment by KonradHoeffner** [comment]
I'm more experienced with Docker now, so I found the error: The mount option must be specified before the image name, for example:

```bash
mkdir /tmp/.kbox
docker run  --name kbox --mount type=bind,source=/tmp/.kbox,target=/root/.kbox aksw/kbox -server -kb "https://www.w3.org/2000/01/rdf-schema"  -install
```
