### ISSUE TITLE
Error installing the Knowledge Bases.

### ISSUE THREAD

**Issue by omarsmak** [AKSW/KBox#7]
Hello,

I was trying to run a DBepdia server using this command:
```
java -jar kbox-v0.0.1-alpha3-RC16.jar -server -kb http://dbpedia.org/3.9/en/full -install
```

But I got the following error:
```
WARNING: Closing storage with uncommited data, this data will be discarded.
Error installing the Knowledge Bases.
```

Thought it only worked with one KB : http://linkedmdb.org

**Comment by digamarx** [comment]
We are back, thanks for your feedback and sorry for the inconvenience.
We were replicating our servers.
From now our users will experience more reliability.

**Comment by omarsmak** [comment]
Thanks a lot :). Just a question, which KB URL that is referring to DBpedia 2016-04?

**Comment by digamarx** [comment]
DBpedia 2016 is beta.
It already has many beta versions and it would be difficult to say exactly which version is available.
It will be available as soon as DBpedia have a stable release version.

**Comment by omarsmak** [comment]
The issue is still persisting, perhaps the jar distribution file is not updated?

**Comment by digamarx** [comment]
Are you trying http://dbpedia.org/3.9/en/full?
What is the error?
Can you copy paste here?
I would like to know if it is after or before derreferencing.
If install is in 100% than it is not the derreferencing, otherwise, you will have another error.

**Comment by omarsmak** [comment]
This is the error:
```
root@kbox:~/ubuntu# java -jar kbox-v0.0.1-alpha3-RC16.jar -server -kb "http://dbpedia.org/2015_10/en/full" -install
Loading Model...
Error installing the Knowledge Bases.
```

Same goes for one of the examples:
```
root@kbox:~/ubuntu# java -jar kbox-v0.0.1-alpha3-RC16.jar -sparql "Select (count(distinct ?s) as ?n) where {?s ?p ?o}" -kb "https://www.w3.org/2000/01/rdf-schema,http://xmlns.com/foaf/0.1" -install

Error exectuting query 'Select (count(distinct ?s) as ?n) where {?s ?p ?o}': null
```
I noticed that you updated `table.kns` yesterday, perhaps you need recompile the final executable jar file?

**Comment by digamarx** [comment]
Cool, it seems you do not have internet access, check it out and let me know...

**Comment by digamarx** [comment]
Ummm, it means you are the lucky one :)...

I am receiving this:

> > java -jar kbox-v0.0.1-alpha3-RC16.jar -kb http://dbpedia.org/3.9/en/full -install
> Installing KB http://dbpedia.org/3.9/en/full
> Installing   0% [>                    ]   0/100, ETA: N/A

So it means you have an error before.
Can you check if you have read/write access in kbox resource folder.

Try to listing it:

https://github.com/AKSW/KBox#listing-the-resource-folder

And change it:

https://github.com/AKSW/KBox#changing-the-resource-folder

Waiting...

**Comment by omarsmak** [comment]
I tried the the same one as yours and it worked:
```
java -jar kbox-v0.0.1-alpha3-RC16.jar -server -kb http://dbpedia.org/3.9/en/full -install
Loading Model...
Installing   0% [>                    ]   0/100, ETA: N/A^Croot@kbox:~/ubuntu# ^C
```

But with another version of DBpedia, the same error:
```
java -jar kbox-v0.0.1-alpha3-RC16.jar -server -kb http://dbpedia.org/2015-10/en -install
Loading Model...
Error installing the Knowledge Bases.
```
```
java -jar kbox-v0.0.1-alpha3-RC16.jar -server -kb http://dbpedia.org/2015-10/en/full -install
Loading Model...
Error installing the Knowledge Bases.
```
```
java -jar kbox-v0.0.1-alpha3-RC16.jar -server -kb http://dbpedia.org/2015_10/en/full -install
Loading Model...
Error installing the Knowledge Bases.
```

**Comment by digamarx** [comment]
Thank you very much for your feedback.
Issue fixed.
Let us know if you have any other issue...

**Comment by omarsmak** [comment]
Awesome! Thanks a lot and have a nice day :)
